yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
]

yatube/users/urls.py
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView,
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView,
    PasswordResetCompleteView)
from django.urls import path

from . import views


app_name = 'users'


urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/', PasswordChangeView.as_view(),
        name='password_change'
    ),
    path(
        'password_change/done/', PasswordChangeDoneView.as_view(),
        name='password_change_done'
    ),
    path(
        'password_reset/', PasswordResetView.as_view(),
        name='password_reset_form'
    ),
    path(
        'password_reset/done/', PasswordResetDoneView.as_view(),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/', PasswordResetCompleteView.as_view(),
        name='password_reset_complete'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Текстовое поле'
    )
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )

    def __str__(self):
        return self.text[:15]

    def get_absolute_url(self):
        return reverse('posts:post_detail', kwargs={'post_id': self.pk})

    class Meta:
        ordering = ('-pub_date',)

yatube/posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import PostForm
from .models import Group, Post, User

POSTS_COUNT = 10


def index(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, POSTS_COUNT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    paginator = Paginator(post_list, POSTS_COUNT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    paginator = Paginator(posts, POSTS_COUNT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'author': author,
        'page_obj': page_obj,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    context = {
        'post': post,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', username=request.user)
    form = PostForm()
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    is_edit = True
    form = PostForm(request.POST, instance=post)
    if form.is_valid():
        form.save()
        return redirect(post)
    if request.user != post.author:
        return redirect(post)
    form = PostForm(instance=post)
    context = {
        'is_edit': is_edit,
        'form': form,
        'post': post,
    }
    return render(request, 'posts/create_post.html', context)

yatube/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
  <h1>Об авторе</h1>
  <p> Здесь будет информация об авторе ... когда-нибудь </p>
  <a href="https://github.com/Lets-dancing">Это ссылка на мою страницу GitHub</a>
{% endblock %}

yatube/templates/about/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
  <div class="row">
    <h2>Вот что я умею</h2>
    {% comment %}
      Боковой блок со списком технологий 
      Займет всю ширину блока на мобильном
      и 25% при размерах экрана ≥768px
    {% endcomment %}
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Python
        </li>
        <li class="list-group-item">
          Django
        </li>
      </ul>
    </aside>
    {% comment %}
      Статья  
      Займет всю ширину блока на мобильном
      и 75% при размерах экрана ≥768px
    {% endcomment %}
    <article class="col-12 col-md-9">
      <p> На framework Django </p>
    </article>
  </div>
{% endblock %}

yatube/templates/base.html
<!DOCTYPE html> 
<html lang="ru">
  {% load static %}          
  <head>
    {% include 'includes/meta.html' %}       
    <title>{% block tittle %}{% endblock %}</title> 
  </head>
  <body>
    <header>
      {% include 'includes/header.html' %}
    </header>  
    <main>
      <div class="container py-5">     
      {% block content %}
        Контент не подвезли :(
      {% endblock %}
      </div>
    </main>
      {% include 'includes/footer.html' %}
  </body>
</html>

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>    
</footer>

yatube/templates/includes/form.html
{% load user_filters %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        {{ entrance }}
      </div>
      <div class="card-body">
        {% if form.errors %}
          {% for field in form %}
            {% for error in field.errors %}            
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endfor %}
          {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
              {{ error|escape }}
            </div>
          {% endfor %}
        {% endif %}
        {% for field in form %}
        <form method="post" 
          {% if action_url %} 
            action="{% url action_url %}" 
          {% endif %} 
        >
          {% csrf_token %}
          <div class="form-group row my-3 p-3" {% if field.field.required %} aria-required="true"{% else %}aria-required="false"{% endif %}>
            <label for="{{ field.id_for_label }}">
              {{ field.label }}
              {% if field.field.required %}
              <span class="required text-danger">*</span>
              {% endif %}
            </label>
            <div>    
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
              <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
              {{ field.help_text|safe }}
              </small>
                {% endif %}
            </div>    
          </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
            {{ button|default:"жми сюда" }}
            </button>
            <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
              {{ reset }}
            </a>
          </div>
        </form>
      </div>
    </div>
  </div>
</div> 

yatube/templates/includes/header.html
{% load static %}
{% with request.resolver_match.view_name as view_name %}
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube</a>
      </a>
      <ul class="nav nav-pills">
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}" 
          href="{% url 'about:author' %}">Об авторе</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}" 
          href="{% url 'about:tech' %}">Технологии</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item"> 
           <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}" 
            href="{% url 'posts:post_create'%}">Новая запись</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:password_change' %}active{% endif %}" 
          href="{% url 'users:password_change' %}">Изменить пароль</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:logout' %}active{% endif %}" 
          href="{% url 'users:logout' %}">Выйти</a>
        </li>
        <li>
          Пользователь: {{ user.username }}
        <li>
        {% else %}
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}" 
          href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}" 
          href="{% url 'users:signup' %}">Регистрация</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>      
{% endwith %}

yatube/templates/includes/meta.html
{% load static %}  
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
  <meta name="msapplication-TileColor" content="#000">
  <meta name="theme-color" content="#ffffff">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
{% if is_edit %}
Редактирование поста
{% else %}
Новый пост
{% endif %}
{% endblock %}
{% block content %}
  {% if is_edit %}
    {% include "includes/form.html" with entrance="Редактировать пост" button="Редактировать" %}
  {% else %}
    {% include "includes/form.html" with entrance="Добавить запись" button="Сохранить" %}
  {% endif %}

{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block content %}
<h1>{{ group.title }}</h1>
  <article>
    {% for post in page_obj %}
    <ul>
      <p>{{ group.description }}</p>
      <li>
        Автор: {{ post.author.get_full_name }}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>      
    <p>
      {{ post.text }}
    </p> 
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </article>
{% endblock %}

yatube/templates/posts/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
  {% for post in page_obj %}
  <article>
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>      
    <p>
      {{ post.text }}
    </p>
    {% if post.group %}   
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}
  {% if not forloop.last %}<hr>{% endif %}
  </article>
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}Пост {{ post|truncatechars:30 }}{% endblock %}
{% block content %}
<div class="row">
<aside class="col-12 col-md-3">
   <ul class="list-group list-group-flush">
      <li class="list-group-item">
         Дата публикации: {{ post.pub_date|date:"d E Y" }} 
      </li>
      {% if post.group %}    
      <li class="list-group-item">
         Группа: {{ post.group.title }}
         <a href="{% url 'posts:group_list' post.group.slug %}">
         все записи группы
         </a>
      </li>
      {% endif %}
      <li class="list-group-item">
         Автор: {{ post.author.get_full_name }}
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
         Всего постов автора:  <span >{{ post.author.posts.count }}</span>
      </li>
      <li class="list-group-item">
         <a href="{% url 'posts:profile' post.author %}">
         все посты пользователя
         </a>
      </li>
   </ul>
</aside>
<article class="col-12 col-md-9">
   <p>{{ post.text }}</p>
</article>
<div class="d-flex justify-content-end">
   {% if request.user == post.author %}
   <button type="submit">
   <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}"> Редактировать пост </a>
   </button>
   {% endif %}
</div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block content %}
<title>Профайл пользователя {{ author.get_full_name }}</title>
<h1>Все посты пользователя {{ author.get_full_name }}</h1>
<h3>Всего постов: {{ author.posts.count }} </h3>   
<article>
{% for post in page_obj %}
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
      <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }} 
    </li>
  </ul>
  <p>
    {{ post.text }} 
  </p>
  <a href={% url 'posts:post_detail' post.pk %}>подробная информация</a>
</article>
{% if post.group %}       
<a href={% url 'posts:group_list' post.group.slug %}>все записи группы</a>
{% endif %}        
{% if not forloop.last %}<hr>{% endif %}
{% include 'posts/includes/paginator.html' %} 
{% endfor %}
{% endblock %}

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
  {% include "includes/form.html" with entrance="Войти на сайт" button="Войти" reset="Забыли пароль?" %}
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  {% include "includes/form.html" with entrance="Зарегистрироваться" button="Зарегистрироваться" %}
{% endblock %}